# fstest.py - Returns a list of places that are not recommended

'''
Input:
Should take in a single argument that specifies
a file path. The file should be a single line
string representation of a Python dictionary of
the form generated by foursquare.py

Output:
Prints a list of all of the places that are not
recommended once by the recommender
Output can be redirected to file for further use
'''

import sys
import codecs
import ast


class Tester:
    def __init__(self,path):
        f = codecs.open(path)
        for line in f:
            self.data = ast.literal_eval(line)

def main():
    if len(sys.argv) == 2:
        t = Tester(sys.argv[1])
        places = []
        recd = []
        for place in t.data:
            places.append(place)
            for rec in t.data[place]:
                if rec[1] not in recd:
                    recd.append(rec[1])


        for place in places:
            if place not in recd:
                print(place)
    else:
        raise RuntimeError("Incorrect number of arguments")

if __name__ == "__main__":
    main()